package com.schedule;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling //SpringBoot 项目在项目启动类上添加 @EnableScheduling 注解即可开启定时任务管理。
public class TestscheduleApplication {

	public static void main(String[] args) {
		SpringApplication.run(TestscheduleApplication.class, args);
	}

}
